theme: jekyll-theme-cayman
title: PDF Slicer
description: A simple application to extract, merge, rotate and reorder pages of PDF documents
github:
  repository_name: PDF Slicer
  latest_release_url: https://github.com/junrrein/pdfslicer/releases/latest
  flathub_url: https://flathub.org/apps/details/com.github.junrrein.PDFSlicer
  owner_name: Julián Unrrein
