theme: jekyll-theme-cayman
title: PFD Slicer
description: A simple application to extract and rotate pages of a PDF document
github:
  repository_name: PDF Slicer
  latest_release_url: https://github.com/junrrein/pdfslicer/releases/latest
  flathub_url: https://flathub.org/apps/details/com.github.junrrein.PDFSlicer
